AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Fraud Detection Multi-Agent System - AWS V1

Parameters:
  OpenAIKeyParameterName:
    Type: String
    Default: /fraud-detection/openai-api-key
    Description: SSM Parameter Store path for OpenAI API key

Globals:
  Function:
    Timeout: 300  # 5 minutes for multi-agent processing
    MemorySize: 2048  # More memory = faster execution
    Tracing: Active  # Enable X-Ray tracing

Resources:
  # S3 bucket for input files (transactions, customer behavior, policies)
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-fraud-input"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"
        MaxAge: 300
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  FraudFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 300
      MemorySize: 2048
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          APP_ENV: aws
          STORAGE_BACKEND: dynamodb
          DDB_TABLE_TRANSACTIONS: !Ref TransactionsTable
          DDB_TABLE_AUDIT: !Ref AuditTable
          DDB_TABLE_HITL: !Ref HitlTable
          VECTOR_DIR: /tmp/vectors
          INPUT_BUCKET: !Ref InputBucket
          LLM_PROVIDER: openai
          EMBEDDINGS_PROVIDER: openai
          WEB_SEARCH_PROVIDER: mock
          OPENAI_KEY_PARAMETER_NAME: !Ref OpenAIKeyParameterName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
        - DynamoDBCrudPolicy:
            TableName: !Ref HitlTable
        - S3ReadPolicy:
            BucketName: !Ref InputBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${OpenAIKeyParameterName}"
    Metadata:
      Dockerfile: Dockerfile.lambda
      DockerContext: .
      DockerTag: fraud-api

  # CloudWatch Alarm for Lambda errors
  FunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-lambda-errors"
      AlarmDescription: Alert when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FraudFunction

  # CloudWatch Alarm for Lambda throttling
  FunctionThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-lambda-throttles"
      AlarmDescription: Alert when Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FraudFunction

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH

  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  HitlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: case_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: case_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: transaction-id-index
          KeySchema:
            - AttributeName: transaction_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  InputBucketName:
    Description: S3 bucket for input files (transactions, behavior, policies)
    Value: !Ref InputBucket
    Export:
      Name: !Sub "${AWS::StackName}-InputBucket"
  
  TransactionsTableName:
    Description: DynamoDB table for transactions
    Value: !Ref TransactionsTable
  
  AuditTableName:
    Description: DynamoDB table for audit trails
    Value: !Ref AuditTable
  
  HitlTableName:
    Description: DynamoDB table for HITL cases
    Value: !Ref HitlTable
  
  FunctionName:
    Description: Lambda function name
    Value: !Ref FraudFunction
