FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

ENV PYTHONPATH=/var/task
ENV APP_ENV=aws
ENV STORAGE_BACKEND=dynamodb
ENV INPUT_DIR=/var/task/.storage/input
ENV PERSISTENCE_DIR=/tmp/state
ENV VECTOR_DIR=/tmp/vectors
ENV LLM_PROVIDER=mock
ENV EMBEDDINGS_PROVIDER=mock
ENV WEB_SEARCH_PROVIDER=mock

CMD ["app.main.handler"]
